-- -----------------------------------------------------
-- user name {from user_1 to user_38}
-- user password {from ThetaPassword_1 to ThetaPassword_38}
-- -----------------------------------------------------

-- Populate users
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_1', 'edc6fdf99a14c51ad23424eb4606050b647b4891acf0534a790a5d0ef2ef7096', 'user_1@example.com', 'First_1', 'Last_1', 'Location_1', 'user_image_1.jpg', 'Description for user 1', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_2', '86333f05c2cd5e51f01250672216d41b48af7f4a0c79e637fa96494bba60baa7', 'user_2@example.com', 'First_2', 'Last_2', 'Location_2', 'user_image_2.jpg', 'Description for user 2', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_3', 'ea9cb150e619b9b406d9e4f646e7482d1ff17c3e08d7018c261463fc644eb7a9', 'user_3@example.com', 'First_3', 'Last_3', 'Location_3', 'user_image_3.jpg', 'Description for user 3', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_4', '5659852915fe11a5aeaf263bfce7952a90c9c8a399f6a15f1243c77c1d7ac9da', 'user_4@example.com', 'First_4', 'Last_4', 'Location_4', 'user_image_4.jpg', 'Description for user 4', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_5', '98a28c40195e8dcd5eab9539b1245b3b8a8906335d03767f0e5b04bb4fa13eb9', 'user_5@example.com', 'First_5', 'Last_5', 'Location_5', 'user_image_5.jpg', 'Description for user 5', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_6', '387949b03f202dedbfac84147a5e3b3070a249a2771cd09824d878db4d69233e', 'user_6@example.com', 'First_6', 'Last_6', 'Location_6', 'user_image_6.jpg', 'Description for user 6', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_7', '718d3b423f4a56a3e3447cb5c8ac2339a3496908c227179a4dbee41320ffd1d7', 'user_7@example.com', 'First_7', 'Last_7', 'Location_7', 'user_image_7.jpg', 'Description for user 7', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_8', '59f0f166a1f6ec7aabd8a67c30f2905a3effd713cda423f07f9248d73db8f108', 'user_8@example.com', 'First_8', 'Last_8', 'Location_8', 'user_image_8.jpg', 'Description for user 8', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_9', 'cdd171b19999bde8a9c6388b1393e84b379ba3eecbfe60a5e07ebe7a358bca5e', 'user_9@example.com', 'First_9', 'Last_9', 'Location_9', 'user_image_9.jpg', 'Description for user 9', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_10', '8dbb10d34ff8f018e78e19325dcee028479cc1783855936ef5387bd7db2ab922', 'user_10@example.com', 'First_10', 'Last_10', 'Location_10', 'user_image_10.jpg', 'Description for user 10', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_11', 'f9bd42b015b329ea06f8e0c0027852ab7076a1c879658b76aef4800bd797fbf9', 'user_11@example.com', 'First_11', 'Last_11', 'Location_11', 'user_image_11.jpg', 'Description for user 11', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_12', 'c7389c3ca075406a52fa101c17b2f21215edd49eb7b87d27c4eca9814ee686c5', 'user_12@example.com', 'First_12', 'Last_12', 'Location_12', 'user_image_12.jpg', 'Description for user 12', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_13', '3963f5e92570ac3fae62b035715379d41c6106ef0bd29df81337ba73de1d5275', 'user_13@example.com', 'First_13', 'Last_13', 'Location_13', 'user_image_13.jpg', 'Description for user 13', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_14', 'e5593e0ef66aaa20178607af5da6cb9348dd75348a425f33aaed7a1ceb31c62e', 'user_14@example.com', 'First_14', 'Last_14', 'Location_14', 'user_image_14.jpg', 'Description for user 14', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_15', 'ea44868d9874fd68eae1c751ee1b27eeddaca7f81ffbfb9fc35859c956d3658b', 'user_15@example.com', 'First_15', 'Last_15', 'Location_15', 'user_image_15.jpg', 'Description for user 15', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_16', '60bd8b40d1f5f3c0086dbc92f16bb21bac8d9ab75439426921ac3f7ceb177d1e', 'user_16@example.com', 'First_16', 'Last_16', 'Location_16', 'user_image_16.jpg', 'Description for user 16', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_17', '570263193aff4fe4f3d82653b4a65d020c6ef20e675c63901655c5b5190743e4', 'user_17@example.com', 'First_17', 'Last_17', 'Location_17', 'user_image_17.jpg', 'Description for user 17', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_18', '0a15bb64998b8e58002ebc8ef08c14270680579494e8961a24b026a3c1d22c27', 'user_18@example.com', 'First_18', 'Last_18', 'Location_18', 'user_image_18.jpg', 'Description for user 18', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_19', '97559a78c7a4bda6c32d393b33b619bede16e1f5a0d3773172ce00da4c994e43', 'user_19@example.com', 'First_19', 'Last_19', 'Location_19', 'user_image_19.jpg', 'Description for user 19', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_20', '52b07eee9415071fce49cdd46de50aa378675bc79af94b19e07df4ed3018c267', 'user_20@example.com', 'First_20', 'Last_20', 'Location_20', 'user_image_20.jpg', 'Description for user 20', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_21', 'b343e97ba8abfa88d2629689db13709250a7b10fa410a9d90ee88d401aa9990d', 'user_21@example.com', 'First_21', 'Last_21', 'Location_21', 'user_image_21.jpg', 'Description for user 21', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_22', '8d967e831e73d355fc17b3faa2d08521bdb5ba3223cf7711402bd379e9ba7829', 'user_22@example.com', 'First_22', 'Last_22', 'Location_22', 'user_image_22.jpg', 'Description for user 22', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_23', 'e735e9a3928ac7809caf5893a2f7bd5e45414fa0795cf0ccafd0df31fbe9ca4b', 'user_23@example.com', 'First_23', 'Last_23', 'Location_23', 'user_image_23.jpg', 'Description for user 23', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_24', '482ed1a542bbf3df0fca4e94611f9813a4238bcf08ccca0340545dbaf7b19ece', 'user_24@example.com', 'First_24', 'Last_24', 'Location_24', 'user_image_24.jpg', 'Description for user 24', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_25', '291eebe2596fe007027231a2c3a1dae3cab9a2bf783163309a98149286e0e2de', 'user_25@example.com', 'First_25', 'Last_25', 'Location_25', 'user_image_25.jpg', 'Description for user 25', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_26', '353b00f3df8d6a8cfbe2776bfc682a458fcc337c1429de36af9cf9aa2c1339fd', 'user_26@example.com', 'First_26', 'Last_26', 'Location_26', 'user_image_26.jpg', 'Description for user 26', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_27', '0a5f704ce9484c0ea408b8b36a259875bbe41b522d3a2fd6518901e85fded7c9', 'user_27@example.com', 'First_27', 'Last_27', 'Location_27', 'user_image_27.jpg', 'Description for user 27', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_28', 'd4624daef5ea2cf8670670ba397a94bbbec23df3747cd644b98a674dd95b5838', 'user_28@example.com', 'First_28', 'Last_28', 'Location_28', 'user_image_28.jpg', 'Description for user 28', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_29', '97b91ea8518591a839abab026d882319faa0c224c0480d419e1c7d58d35ffe9c', 'user_29@example.com', 'First_29', 'Last_29', 'Location_29', 'user_image_29.jpg', 'Description for user 29', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_30', '697236a9874d8dc9fdd994389c167070c832166242cdc3f98e42a7f270bfd46c', 'user_30@example.com', 'First_30', 'Last_30', 'Location_30', 'user_image_30.jpg', 'Description for user 30', 'voter');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_31', '0269c98a97261120390ec36213e09582f3f6829d680b9120ba1f60d7c9b24fff', 'user_31@example.com', 'First_31', 'Last_31', 'Location_31', 'user_image_31.jpg', 'Description for user 31', 'scrutineer');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_32', 'bb3fcd6a5f38f4b7d7d825b2d566aa0df78265285f3042821f78c1692f218746', 'user_32@example.com', 'First_32', 'Last_32', 'Location_32', 'user_image_32.jpg', 'Description for user 32', 'scrutineer');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_33', '0a0d194325b93d9b1173cf70ade298a507c51cfb7f1627fef018c727132e4f59', 'user_33@example.com', 'First_33', 'Last_33', 'Location_33', 'user_image_33.jpg', 'Description for user 33', 'scrutineer');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_34', 'b22d02cccbc88c5a6f79256445e60e3a8c54fca8f5c1e9b2607206454453e3f1', 'user_34@example.com', 'First_34', 'Last_34', 'Location_34', 'user_image_34.jpg', 'Description for user 34', 'scrutineer');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_35', '2c7ee3449ec682aeccb425c194b8a0e5f99d2b8e09a28330f0966110f6165211', 'user_35@example.com', 'First_35', 'Last_35', 'Location_35', 'user_image_35.jpg', 'Description for user 35', 'scrutineer');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_36', 'b489e81139eb07114053931ed7887a61ad3506f1c391d308e1026d80c1c91718', 'user_36@example.com', 'First_36', 'Last_36', 'Location_36', 'user_image_36.jpg', 'Description for user 36', 'admin');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_37', 'f0c089be827d083fa9b407cb9d894b9fc4e0795fadb979b52aca4190cf5d8fe8', 'user_37@example.com', 'First_37', 'Last_37', 'Location_37', 'user_image_37.jpg', 'Description for user 37', 'admin');
INSERT INTO users (username, password_hash, email, first_name, last_name, location, user_image, user_description, role) VALUES ('user_38', 'f6c69cfb3acc1fe276886e8234938451c05dc9c17480bc7a25b5061bedf4d80e', 'user_38@example.com', 'First_38', 'Last_38', 'Location_38', 'user_image_38.jpg', 'Description for user 38', 'super_admin');

-- Populate competitions
INSERT INTO competitions (title, category, competition_description, start_date, end_date, is_public, competition_image, result_finalised) VALUES ('NZ Native Tree of the Year', 'Nature', 'Vote for the NZ Native Tree of the Year', '2024-08-04 07:05:36', '2024-08-17 07:05:36', '1', 'competition_image_1.jpg', '0');
INSERT INTO competitions (title, category, competition_description, start_date, end_date, is_public, competition_image, result_finalised) VALUES ('NZ Native Flower of the Year', 'Nature', 'Vote for the NZ Native Flower of the Year', '2024-07-23 07:05:36', '2024-08-27 07:05:36', '1', 'competition_image_2.jpg', '0');
INSERT INTO competitions (title, category, competition_description, start_date, end_date, is_public, competition_image, result_finalised) VALUES ('NZ Native Cat of the Year', 'Animal', 'Vote for the NZ Native Cat of the Year', '2024-07-28 07:05:36', '2024-09-06 07:05:36', '1', 'competition_image_3.jpg', '0');
INSERT INTO competitions (title, category, competition_description, start_date, end_date, is_public, competition_image, result_finalised) VALUES ('NZ Bird of the Year', 'Animal', 'Vote for the NZ Bird of the Year', '2024-06-08 07:05:36', '2024-07-08 07:05:36', '1', 'competition_image_4.jpg', '1');
INSERT INTO competitions (title, category, competition_description, start_date, end_date, is_public, competition_image, result_finalised) VALUES ('NZ Dog of the Year', 'Animal', 'Vote for the NZ Dog of the Year', '2024-06-23 07:05:36', '2024-07-23 07:05:36', '1', 'competition_image_5.jpg', '0');
INSERT INTO competitions (title, category, competition_description, start_date, end_date, is_public, competition_image, result_finalised) VALUES ('NZ Game of the Year', 'Game', 'Vote for the NZ Game of the Year', '2024-05-09 07:05:36', '2024-06-08 07:05:36', '1', 'competition_image_6.jpg', '0');

-- Populate competitors
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Oak', 'Oaks are robust, long-living trees known for their strong, durable wood and lobed leaves. They produce acorns, which are a key food source for wildlife.', 'tree_image_1.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Maple', 'Maples are famous for their distinctive, palmate leaves and vibrant fall colors. The sugar maple is particularly well-known for producing maple syrup.', 'tree_image_2.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Pine', 'Pines are evergreen conifers with long, needle-like leaves and woody cones. They are commonly found in temperate and subtropical regions.', 'tree_image_3.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Birch', 'Birches are slender, deciduous trees with characteristic white or silver bark that peels in thin layers. Their small, triangular leaves turn yellow in autumn.', 'tree_image_4.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Willow', 'Willows are graceful, deciduous trees with long, slender branches that often droop. They thrive in moist soils and are commonly found near water bodies.', 'tree_image_5.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Cedar', 'Cedars are evergreen conifers with fragrant wood, needle-like leaves, and large, barrel-shaped cones. They are often used in furniture and construction.', 'tree_image_6.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Spruce', 'Spruces are tall, conical evergreen trees with sharp, needle-like leaves and hanging cones. They are commonly used as Christmas trees.', 'tree_image_7.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Redwood', 'Redwoods are among the tallest trees in the world, with thick, reddish bark and evergreen foliage. They are native to the coastal regions of California.', 'tree_image_8.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Cherry', 'Cherry trees are known for their beautiful, fragrant blossoms in spring and their small, red fruits. They have smooth, reddish-brown bark.', 'tree_image_9.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Elm', 'Elms are large, deciduous trees with arching branches and serrated, oval leaves. They are known for their stately appearance and historical significance.', 'tree_image_10.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Cypress', 'Cypresses are conifers with scale-like leaves and small, round cones. They are often found in wetlands and are known for their durability in water.', 'tree_image_11.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Sycamore', 'Sycamores are large, deciduous trees with broad, lobed leaves and mottled bark that peels away to reveal a lighter inner bark.', 'tree_image_12.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Fir', 'Firs are evergreen conifers with flat, needle-like leaves and upright cones. They are commonly used as Christmas trees due to their symmetrical shape.', 'tree_image_13.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Aspen', 'Aspens are tall, deciduous trees with smooth, white bark and leaves that tremble in the wind. They are known for forming large groves through root sprouting.', 'tree_image_14.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Beech', 'Beeches are large, deciduous trees with smooth, gray bark and oval, toothed leaves. They produce small nuts called beechnuts, which are edible.', 'tree_image_15.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Ash', 'Ash trees are tall, deciduous trees with compound leaves and strong, straight-grained wood. They are often used in making furniture and baseball bats.', 'tree_image_16.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Magnolia', 'Magnolias are ornamental trees with large, fragrant flowers and glossy, dark green leaves. They are among the oldest flowering plants.', 'tree_image_17.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Poplar', 'Poplars are fast-growing, deciduous trees with triangular leaves and grayish bark. They are often used in timber production and for windbreaks.', 'tree_image_18.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Olive', 'Olive trees are small, evergreen trees with silver-green leaves and gnarled trunks. They are known for producing olives and olive oil.', 'tree_image_19.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (1, 'Hemlock', 'Hemlocks are evergreen conifers with feathery, needle-like leaves and small, pendant cones. They thrive in cool, moist environments.', 'tree_image_20.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Rose', 'A classic flower symbolizing love and beauty, with a variety of colors and a delightful fragrance.', 'flower_image_1.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Tulip', 'Known for its elegant shape and vibrant colors, tulips are popular in spring gardens.', 'flower_image_2.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Daisy', 'A cheerful flower with white petals and a yellow center, symbolizing purity and innocence.', 'flower_image_3.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Lily', 'A graceful flower with large, trumpet-shaped blooms, often associated with purity and refined beauty.', 'flower_image_4.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Sunflower', 'A tall, bright yellow flower known for its large size and its tendency to turn towards the sun.', 'flower_image_5.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Orchid', 'Exotic and diverse, orchids are known for their intricate and beautiful blooms.', 'flower_image_6.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Iris', 'With its unique and delicate petals, the iris symbolizes faith and wisdom.', 'flower_image_7.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Peony', 'Known for its large, fragrant blooms and lush petals, peonies are often associated with romance and prosperity.', 'flower_image_8.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Chrysanthemum', 'A symbol of autumn, chrysanthemums are known for their diverse shapes and vibrant colors.', 'flower_image_9.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Jasmine', 'A delicate flower known for its sweet fragrance, jasmine is often used in perfumes and teas.', 'flower_image_10.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Marigold', 'Bright and cheerful, marigolds are known for their vivid orange and yellow blooms, often used in gardens for pest control.', 'flower_image_11.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Lavender', 'Famed for its soothing scent, lavender is used in aromatherapy and cooking, with beautiful purple spikes of flowers.', 'flower_image_12.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Hibiscus', 'Exotic and colorful, hibiscus flowers are often used in teas and are admired for their large, trumpet-shaped blooms.', 'flower_image_13.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Gardenia', 'Known for its creamy white flowers and rich, sweet fragrance, gardenias are a popular choice for floral arrangements.', 'flower_image_14.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Calla Lily', 'Elegant and striking, calla lilies are characterized by their smooth, trumpet-shaped flowers and are often used in formal arrangements.', 'flower_image_15.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Begonia', 'With vibrant colors and unique leaf shapes, begonias are popular in shaded gardens and indoor settings.', 'flower_image_16.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Snapdragon', 'Distinctive for its dragon-shaped blooms, snapdragons come in a variety of colors and are great for adding vertical interest to gardens.', 'flower_image_17.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Poppy', 'Poppies are known for their delicate, papery petals and are often associated with remembrance and peace.', 'flower_image_18.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Camellia', 'With its elegant, rose-like blooms, camellias are often found in gardens and are valued for their beautiful foliage.', 'flower_image_19.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (2, 'Honeysuckle', 'Honeysuckle flowers are known for their sweet fragrance and are often used in perfumes and home gardens.', 'flower_image_20.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Siamese', 'A sleek, elegant breed known for its striking blue eyes, short coat, and vocal nature.', 'cat_image_1.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Maine Coon', 'One of the largest domesticated cat breeds, known for its friendly personality and tufted ears.', 'cat_image_2.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Persian', 'A long-haired breed with a distinctive flat face and luxurious coat, known for its calm demeanor.', 'cat_image_3.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Bengal', 'Known for its leopard-like spots and energetic personality, Bengals are an active and playful breed.', 'cat_image_4.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Sphynx', 'A hairless breed known for its wrinkled skin and affectionate nature, Sphynxes are friendly and curious.', 'cat_image_5.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Ragdoll', 'A large, affectionate breed that goes limp when picked up, known for its blue eyes and semi-long coat.', 'cat_image_6.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Abyssinian', 'One of the oldest known cat breeds, Abyssinians are known for their slender build and active, playful behavior.', 'cat_image_7.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Scottish Fold', 'Distinguished by its unique folded ears and sweet disposition, the Scottish Fold is a loving and playful breed.', 'cat_image_8.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'British Shorthair', 'Known for its round face and dense, plush coat, this breed is calm, easygoing, and friendly.', 'cat_image_9.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Norwegian Forest Cat', 'A large, robust breed with a thick coat suited for cold climates, known for its friendly and intelligent nature.', 'cat_image_10.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Siberian', 'A strong, large breed with a dense, water-repellent coat, Siberians are affectionate and good-natured.', 'cat_image_11.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Oriental Shorthair', 'With a sleek, slender body and a wide range of colors, this breed is known for its intelligence and vocal nature.', 'cat_image_12.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Himalayan', 'A long-haired breed similar to the Persian but with distinctive blue eyes and a pointed coat pattern.', 'cat_image_13.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Tonkinese', 'A playful and affectionate breed with a medium-length coat, known for its striking eyes and lively personality.', 'cat_image_14.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Manx', 'Recognizable by its taillessness or short tail, the Manx is known for its friendly and easygoing nature.', 'cat_image_15.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Singapura', 'One of the smallest cat breeds, Singapura is known for its lively and curious nature and its sleek coat.', 'cat_image_16.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Burmese', 'A breed with a sleek, muscular body and expressive eyes, Burmese cats are known for their affectionate and playful behavior.', 'cat_image_17.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Russian Blue', 'Known for its dense blue-gray coat and striking green eyes, the Russian Blue is a calm and reserved breed.', 'cat_image_18.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'LaPerm', 'Distinguished by its curly coat and friendly demeanor, the LaPerm is a playful and affectionate breed.', 'cat_image_19.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (3, 'Cornish Rex', 'Known for its wavy coat and large ears, the Cornish Rex is a playful and active breed with a unique appearance.', 'cat_image_20.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Bald Eagle', 'A large bird of prey with a distinctive white head and tail, known for its powerful beak and keen eyesight.', 'bird_image_1.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Peregrine Falcon', 'The fastest bird in the world, recognized by its sharp talons and keen hunting skills.', 'bird_image_2.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'African Grey Parrot', 'Known for its exceptional intelligence and ability to mimic human speech.', 'bird_image_3.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Harpy Eagle', 'A powerful raptor with striking black-and-white plumage and formidable talons.', 'bird_image_4.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Snowy Owl', 'Recognizable by its white plumage and yellow eyes, this owl is adapted to cold environments.', 'bird_image_5.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Golden Eagle', 'A large and majestic bird of prey known for its golden-brown feathers and impressive wingspan.', 'bird_image_6.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Andean Condor', 'One of the largest flying birds, known for its enormous wingspan and soaring flight.', 'bird_image_7.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Scarlet Macaw', 'A colorful parrot with vivid red, yellow, and blue feathers, known for its loud calls and social behavior.', 'bird_image_8.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Kingfisher', 'Recognizable by its vibrant plumage and sharp bill, this bird is known for its fishing skills.', 'bird_image_9.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Great Horned Owl', 'A large owl with prominent ear tufts and a distinctive hooting call.', 'bird_image_10.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Hummingbird', 'A tiny bird known for its rapid wing beats and ability to hover in place while feeding on nectar.', 'bird_image_11.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Barn Owl', 'Recognizable by its heart-shaped face and silent flight, this owl hunts small mammals at night.', 'bird_image_12.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Red-tailed Hawk', 'A common raptor with a distinctive red tail and keen hunting abilities.', 'bird_image_13.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Kea', 'A large, intelligent parrot native to New Zealand, known for its playful behavior and bright green feathers.', 'bird_image_14.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Secretary Bird', 'A large raptor with long legs and a distinctive head crest, known for its unique hunting technique.', 'bird_image_15.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Mandarin Duck', 'A strikingly colorful duck with elaborate plumage, known for its vibrant appearance.', 'bird_image_16.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'American Robin', 'A common songbird with a red breast and melodious song, often associated with the arrival of spring.', 'bird_image_17.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Creeper', 'A small, insectivorous bird known for its unique climbing ability and cryptic plumage.', 'bird_image_18.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'European Bee-eater', 'A colorful bird known for its vivid plumage and diet of bees and other insects.', 'bird_image_19.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (4, 'Little Blue Heron', 'A wading bird with striking blue-gray plumage and a graceful hunting style in shallow waters.', 'bird_image_20.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Labrador Retriever', 'Friendly and outgoing, Labrador Retrievers are known for their loyalty and intelligence. They make excellent family pets and working dogs.', 'dog_image_1.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'German Shepherd', 'Highly versatile and intelligent, German Shepherds are known for their courage and ability to excel in various roles including service and police work.', 'dog_image_2.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Golden Retriever', 'Affectionate and friendly, Golden Retrievers are known for their gentle nature and are great with families and children.', 'dog_image_3.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'French Bulldog', 'Compact and playful, French Bulldogs are known for their distinctive bat-like ears and are great companions in small living spaces.', 'dog_image_4.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Bulldog', 'Recognizable by their wrinkled face and pushed-in nose, Bulldogs are known for their calm and friendly demeanor.', 'dog_image_5.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Beagle', 'Friendly and curious, Beagles are known for their excellent sense of smell and playful nature.', 'dog_image_6.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Poodle', 'Intelligent and elegant, Poodles come in three sizes and are known for their hypoallergenic coat and versatility in training.', 'dog_image_7.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Rottweiler', 'Strong and confident, Rottweilers are known for their protective nature and loyalty to their families.', 'dog_image_8.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Yorkshire Terrier', 'Small but bold, Yorkshire Terriers are known for their long, silky coat and lively personality.', 'dog_image_9.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Boxer', 'Energetic and playful, Boxers are known for their strength and affectionate nature, making them great family dogs.', 'dog_image_10.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Dachshund', 'With their long bodies and short legs, Dachshunds are known for their lively and courageous personality.', 'dog_image_11.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Siberian Husky', 'Known for their striking blue eyes and friendly demeanor, Siberian Huskies are energetic and enjoy being part of an active family.', 'dog_image_12.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Cocker Spaniel', 'With their long ears and affectionate nature, Cocker Spaniels are known for their gentle temperament and love for families.', 'dog_image_13.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Shih Tzu', 'Small and friendly, Shih Tzus are known for their long, flowing coat and affectionate nature.', 'dog_image_14.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Chihuahua', 'Tiny but bold, Chihuahuas are known for their big personalities and loyalty to their owners.', 'dog_image_15.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Great Dane', 'Known for their large size and gentle nature, Great Danes are affectionate and good-natured.', 'dog_image_16.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Pug', 'With their wrinkled faces and playful personalities, Pugs are known for their charm and affectionate nature.', 'dog_image_17.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Shetland Sheepdog', 'Intelligent and agile, Shetland Sheepdogs are known for their herding abilities and friendly demeanor.', 'dog_image_18.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Maltese', 'Known for their long, white coat and lively personality, Maltese dogs are affectionate and great for families.', 'dog_image_19.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (5, 'Australian Shepherd', 'Energetic and intelligent, Australian Shepherds are known for their herding skills and versatility in training.', 'dog_image_20.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Chess', 'A strategic board game where players move pieces to checkmate the opponent’s king.', 'game_image_1.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Monopoly', 'A real estate trading game where players buy, sell, and trade properties to become the wealthiest player.', 'game_image_2.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Scrabble', 'A word game where players use letter tiles to create words on a game board for points.', 'game_image_3.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Settlers of Catan', 'A strategy board game where players collect resources and build settlements to earn victory points.', 'game_image_4.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Risk', 'A strategy board game of global domination where players control armies to conquer territories.', 'game_image_5.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Ticket to Ride', 'A railway-themed board game where players collect train cards to claim railway routes across a map.', 'game_image_6.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Pandemic', 'A cooperative board game where players work together to prevent global outbreaks of diseases.', 'game_image_7.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Clue', 'A mystery board game where players solve a murder by deducing the culprit, weapon, and location.', 'game_image_8.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Battleship', 'A strategy game where players try to sink each other’s fleet of ships by guessing their locations on a grid.', 'game_image_9.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Codenames', 'A word game where players give one-word clues to help their team guess the correct words on the board.', 'game_image_10.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Twister', 'A physical game where players place their hands and feet on colored circles on a mat based on a spinner’s instructions.', 'game_image_11.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Pictionary', 'A drawing game where players draw clues for their team to guess a specific word or phrase.', 'game_image_12.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Apples to Apples', 'A party game where players match nouns to adjectives to create humorous or fitting combinations.', 'game_image_13.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Charades', 'A word-guessing game where players act out a word or phrase without speaking while their team guesses.', 'game_image_14.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'The Game of Life', 'A board game simulating a person’s journey through life, including career, family, and financial decisions.', 'game_image_15.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Guess Who?', 'A two-player game where players ask yes/no questions to deduce the opponent’s mystery character.', 'game_image_16.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Uno', 'A card game where players match colors or numbers and use special cards to win by getting rid of all their cards.', 'game_image_17.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Sorry!', 'A board game where players move pieces around the board and try to send opponents’ pieces back to start.', 'game_image_18.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Operation', 'A game where players use tweezers to remove body parts from a game board without setting off the buzzer.', 'game_image_19.jpg');
INSERT INTO competitors (competition_id, competitor_name, competitor_description, competitor_image) VALUES (6, 'Jenga', 'A physical game where players remove wooden blocks from a tower and place them on top without collapsing the structure.', 'game_image_20.jpg');

-- Populate votes
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (11, 1, 2, '192.168.1.197');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (3, 1, 8, '192.168.1.197');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (14, 1, 19, '192.168.1.197');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (17, 1, 15, '192.168.1.241');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (3, 1, 29, '192.168.1.241');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (12, 1, 16, '192.168.1.241');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (11, 1, 11, '192.168.1.241');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (6, 1, 4, '192.168.1.241');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (8, 1, 23, '192.168.1.153');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (13, 1, 20, '192.168.1.153');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (19, 1, 18, '192.168.1.153');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (15, 1, 10, '192.168.1.97');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (11, 1, 12, '192.168.1.97');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (7, 1, 27, '192.168.1.71');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (11, 1, 14, '192.168.1.71');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (19, 1, 22, '192.168.1.71');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (12, 1, 17, '192.168.1.103');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (19, 1, 6, '192.168.1.250');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (3, 1, 1, '192.168.1.9');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (14, 1, 5, '192.168.1.225');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (28, 2, 18, '192.168.1.203');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (25, 2, 1, '192.168.1.163');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (32, 2, 20, '192.168.1.22');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (35, 2, 19, '192.168.1.179');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (39, 2, 16, '192.168.1.119');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (33, 2, 25, '192.168.1.114');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (34, 2, 28, '192.168.1.226');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (40, 2, 13, '192.168.1.143');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (30, 2, 3, '192.168.1.184');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (33, 2, 26, '192.168.1.185');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (32, 2, 21, '192.168.1.28');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (27, 2, 27, '192.168.1.149');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (35, 2, 2, '192.168.1.229');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (40, 2, 15, '192.168.1.143');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (39, 2, 24, '192.168.1.168');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (24, 2, 4, '192.168.1.17');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (21, 2, 10, '192.168.1.131');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (32, 2, 7, '192.168.1.102');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (25, 2, 8, '192.168.1.117');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (25, 2, 30, '192.168.1.250');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (41, 3, 3, '192.168.1.209');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (41, 3, 24, '192.168.1.181');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (43, 3, 2, '192.168.1.247');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (56, 3, 28, '192.168.1.4');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (55, 3, 11, '192.168.1.163');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (51, 3, 6, '192.168.1.222');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (54, 3, 15, '192.168.1.217');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (59, 3, 5, '192.168.1.44');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (54, 3, 17, '192.168.1.91');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (58, 3, 20, '192.168.1.88');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (52, 3, 18, '192.168.1.225');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (55, 3, 27, '192.168.1.98');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (43, 3, 22, '192.168.1.175');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (59, 3, 14, '192.168.1.107');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (55, 3, 29, '192.168.1.153');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (41, 3, 21, '192.168.1.220');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (58, 3, 7, '192.168.1.165');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (57, 3, 9, '192.168.1.84');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (60, 3, 10, '192.168.1.39');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address) VALUES (57, 3, 13, '192.168.1.159');

-- Populate past competition votes
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (75, 4, 5, '192.168.1.109', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (65, 4, 9, '192.168.1.198', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (79, 4, 18, '192.168.1.107', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (65, 4, 22, '192.168.1.154', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (75, 4, 17, '192.168.1.216', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (61, 4, 30, '192.168.1.133', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (67, 4, 10, '192.168.1.158', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (77, 4, 2, '192.168.1.86', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (70, 4, 14, '192.168.1.166', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (71, 4, 6, '192.168.1.253', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (66, 4, 12, '192.168.1.18', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (67, 4, 24, '192.168.1.250', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (77, 4, 28, '192.168.1.125', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (73, 4, 21, '192.168.1.110', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (76, 4, 3, '192.168.1.17', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (66, 4, 26, '192.168.1.203', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (68, 4, 29, '192.168.1.181', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (68, 4, 27, '192.168.1.35', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (78, 4, 23, '192.168.1.198', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (72, 4, 1, '192.168.1.68', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (86, 5, 29, '192.168.1.167', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (83, 5, 18, '192.168.1.247', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (86, 5, 13, '192.168.1.65', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (91, 5, 17, '192.168.1.166', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (100, 5, 16, '192.168.1.142', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (84, 5, 8, '192.168.1.242', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (89, 5, 26, '192.168.1.138', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (91, 5, 5, '192.168.1.167', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (84, 5, 1, '192.168.1.152', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (92, 5, 6, '192.168.1.24', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (89, 5, 10, '192.168.1.60', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (96, 5, 19, '192.168.1.72', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (91, 5, 12, '192.168.1.238', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (97, 5, 30, '192.168.1.40', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (98, 5, 23, '192.168.1.41', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (93, 5, 15, '192.168.1.156', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (94, 5, 7, '192.168.1.26', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (97, 5, 2, '192.168.1.172', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (100, 5, 3, '192.168.1.218', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (94, 5, 4, '192.168.1.240', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (118, 6, 28, '192.168.1.185', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (103, 6, 16, '192.168.1.63', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (116, 6, 4, '192.168.1.95', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (112, 6, 12, '192.168.1.223', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (113, 6, 18, '192.168.1.120', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (119, 6, 13, '192.168.1.155', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (101, 6, 3, '192.168.1.159', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (109, 6, 5, '192.168.1.237', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (112, 6, 9, '192.168.1.168', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (119, 6, 25, '192.168.1.92', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (107, 6, 8, '192.168.1.37', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (101, 6, 20, '192.168.1.133', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (120, 6, 30, '192.168.1.205', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (114, 6, 7, '192.168.1.17', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (120, 6, 14, '192.168.1.205', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (116, 6, 21, '192.168.1.30', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (112, 6, 1, '192.168.1.220', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (101, 6, 29, '192.168.1.2', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (118, 6, 23, '192.168.1.221', 'valid');
INSERT INTO votes (competitor_id, competition_id, user_id, ip_address, status) VALUES (118, 6, 26, '192.168.1.90', 'valid');
